version: 1.0.{build}

# AppVeyor clone is not recursive, so we need to to init submodules manually
install:
  - git submodule update --init --recursive

build_script:
- cmd: >-
    call scripts/visualc/build_msvc_2015.bat

artifacts:
- path: 'upload\psmoveapi-*.zip'

test: off
