sudo: required

dist: trusty

language:
  - cpp

before_install:
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
  - sudo add-apt-repository --yes ppa:hlprasu/swig-trusty-backports

install:
  - git submodule update --init --recursive

script:
  - ./build_scripts/ubuntu/build.sh
