matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      compiler: clang
    - os: osx
      osx_image: xcode8.1
      language: cpp
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:kubuntu-ppa/backports; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:hlprasu/swig-trusty-backports; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -q -y mingw-w64 g++-mingw-w64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --force cmake automake autoconf libtool swig || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink libtool ; brew link --overwrite libtool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "\$PATH"; find /usr/local/bin; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then glibtoolize --version ; echo "RESULT=$?"; fi

install:
  - git submodule update --init --recursive
  - git fetch --tags
  - git fetch --unshallow || true

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PATH:$JAVA_HOME/bin; bash -e -x ./contrib/build_scripts/debian/build-ubuntu; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -e -x ./contrib/build_scripts/debian/cross-compile-mingw64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -e -x ./contrib/build_scripts/osx/build-osx-snapshot; fi
