language:
  - cpp

install:
  - git submodule update --init --recursive

addons:
  apt:
    sources:
    - kubuntu-backports
    packages:
    - build-essential
    - cmake
    - libudev-dev
    - libbluetooth-dev
    - libv4l-dev
    - libopencv-dev
    - freeglut3-dev

script:
  - ./build_scripts/ubuntu/build.sh
